export const loadingScreenFacts = [
  "Sortiere den Keller aus. Nein, nicht morgen. Jetzt.",
  "Beschrifte deine Kisten. Du wirst es dir später danken.",
  "Denk an die Ummeldung. Das Internet vergisst nie, aber Ämter schon.",
  "Ein Umzug ist die perfekte Gelegenheit, um endlich den ungeliebten Pullover loszuwerden.",
  "Miss deine Möbel aus. Und die Türen. Und den Aufzug.",
  "Schlafe ausreichend. Umzugskartons sind schwerer, als sie aussehen.",
  "Freunde, die beim Umzug helfen, sind wahre Freunde. Bestechung mit Pizza ist erlaubt.",
  "Der Tag des Umzugs ist der einzige Tag, an dem du ungestraft den ganzen Tag Jogginghosen tragen kannst.",
  "Du hast mehr Zeug, als du denkst. Viel mehr.",
  "Vergiss nicht, den Kühlschrank abzutauen. Eine Lektion, die man nur einmal lernt.",
  "Mach Fotos von den Kabeln deiner Elektrogeräte. Du wirst sie brauchen.",
  "Packe eine 'Erste-Nacht-Box' mit allem, was du sofort brauchst.",
  "Atme tief durch. Es ist nur ein Umzug.",
  "Die meisten Ehen überleben einen Umzug. Deine auch.",
  "Ein Umzug ohne Kratzer im Parkett ist wie ein Schiff ohne Ratten – ein Mythos.",
];
